version: "2.4"

services:

  service1:
    build:
      context: ./services/service1
    scale: 1
    mem_limit: 128m
    environment:
      - NATSURL=nats://nats:4222
      - JAEGER=http://jaeger:14268/api/traces
    depends_on:
      - nats
      - jaeger

  service2:
    build:
      context: ./services/service2
    scale: 1
    mem_limit: 128m
    environment:
      - NATSURL=nats://nats:4222
      - JAEGER=http://jaeger:14268/api/traces
    depends_on:
      - nats
      - jaeger

  nats:
    container_name: test-nats
    image: nats:1.4.1
    command: ["-DV", "-c", "/etc/gnatsd.conf"]
    hostname: nats-server
    restart: always
    mem_limit: 256m
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    volumes:
      - ./config/nats/gnatsd.conf:/etc/gnatsd.conf

  jaeger:
    image: jaegertracing/all-in-one:1.13.1
    container_name: test-jaeger
    mem_limit: 512m
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
